print()
print("Thushiv & Thushya")
print("12")
print("i want to be a independent person('self love')")
print('"welcome all to the lovely place"')
print("Hello Pavi\nHello Pavi\nHello Pavi")
print("Hello"+"Pavi")
print("Hello"" ""Pavi")