Name=input("what is your name?"+" ")
Mobile_Number=(input("what is your mobile number?"+" "))
print(f"UserName: {Name}\nMobile_number: {Mobile_Number}")
length_of_Name=len(Name)
length_of_Mobile_Number=len(Mobile_Number)
print(length_of_Name,length_of_Mobile_Number )
Identitycard=input("what is the Identitycard Name?" )
ID=input("What is the ID Number?" )
print(Identitycard+" " + ID)
