Name=input("what is your name?"+" ")
Mobilenumber=(input("what is your mobile number?"+" "))
print(f"UserName {Name} mobilenumber {Mobilenumber}")
lengthofName=len(Name)
lengthofMobilenumber=len(Mobilenumber)
print(lengthofName,lengthofMobilenumber )
Identitycard=input("what is the Identitycard?" )
ID=input("What is the User ID Number?" )
print(Identitycard+" " + ID)
